double HurtgenCoding(int, int, int, int *, int *, int *, int *, int *);
double SaupeCoding(int, int, int, int *, int *, int *, int *, int *);
double FisherCoding(int, int, int, int *, int *, int *, int *, int *);
double Mc_SaupeCoding(int, int, int, int *, int *, int *, int *, int *);
double MassCenterCoding(int, int, int, int *, int *, int *, int *, int *);
double Saupe_FisherCoding(int, int, int, int *, int *, int *, int *, int *);
double entropy(int, int, int, int);
double variance(int, int, int, int);
double variance_2(int, double **, int, int);
int hurtgen_class(int, double **);
int pack(int, long, FILE *);
int variance_class(int, double **);
kdtree *kdtree_build(float **, int, int);
void ComputeAverageFactorMc();
void ComputeFeatVectDimSaupe();
void ComputeMcVectors(double **, double **, int, int, double *);
void ComputeSaupeVectors(double **, int, int, float *);
void FisherIndexing(int, int);
void HurtgenIndexing(int, int);
void MassCenterIndexing(int, int);
void SaupeIndexing(int, int);
void Mc_SaupeIndexing(int, int);
void Saupe_FisherIndexing(int, int);
void contraction(double **, PIXEL **, int, int);
void fatal(char *);
void flips(int, double **, double **, int);
int kdtree_search(float *, float **, int, kdtree *, float, int, int *);
void ComputeMc(double **, int, double *, double *, int);
void newclass(int, double **, int *, int *);
void getopt_enc(int, char **);
void getopt_dec(int, char **);
void quadtree(int, int, int, double, double, double);
void readimage_raw(char *);
void readimage_pgm(char *, int *, int *);
void help_enc();

long unpack(int size, FILE *fin);
void read_transformations(int atx, int aty, int size);
void writeimage_pgm(char *, PIXEL **, int, int);
void writeimage_raw(char *, PIXEL **, int, int);
void writeimage_pipe(FILE *, PIXEL **, int, int);
void smooth_image();
void zooming(double);
void help_dec();
void iterative_decoding(int, int, double);
void piramidal_decoding(int);
